### ISSUE TITLE
"Pages" not actually plural

### ISSUE THREAD

**Issue by drewbitt** [ButterCMS/buttercms-gridsome-plugin#7]
Defining "pages" in gridsome.config.js only allows for a single page.
https://github.com/ButterCMS/gridsome-source-buttercms/blob/96688f2a6a112636c8ce7e8e81f5cd37c36a9fd0/index.js#L9

gridsome-source-buttercms
```
if (this.options.pages) {
   const page = await this.client.page.retrieve('*', this.options.pages)
```
buttercms
```
retrieve: function(page_type, page_slug, options) {
    return this._conn.get('pages/'+page_type+'/'+page_slug+'/', options)
  }
```
Single page only
I would assume a list should be allowed for the pages property

**Comment by drewbitt** [comment]
There is still no multiple page support 9 months later.

**Comment by jakelumetta** [comment]
Hey @drewbitt Thanks for the note. Sorry notifications were not properly set up for this plugin so we missed your feedback. We've corrected that and are working on an update.

**Comment by jakelumetta** [comment]
Can you try now with version 2.0.0 @drewbitt ?
