### ISSUE TITLE
Page locales

### ISSUE THREAD

**Issue by drewbitt** [ButterCMS/buttercms-gridsome-plugin#8]
Feature request. Getting locales, either singular or multiple, is not supported.

**Comment by jakelumetta** [comment]
Hey @drewbitt Thanks for the note. Sorry notifications were not properly set up for this plugin so we missed your feedback. We've corrected that and are working on an update.

**Comment by jakelumetta** [comment]
Can you try now with version 2.0.0 @drewbitt ?
